image: docker/compose:latest

stages:
  - build
  - deploy-testing

build:
  script:
    - docker login repo.abanicon.com:5050 -u gitlab-ci/cd -p${registery_pass}
    - docker-compose build
    - docker-compose push
    - docker-compose down -v --rmi local --remove-orphans
  tags:
    - websocket
  stage: build

deploy-testing:
  variables:
    ABAN_BACKEND_DEBUG_MODE: "True"
  script:
    - docker login repo.abanicon.com:5050 -u gitlab-ci/cd -p${registery_pass}
    - docker-compose -H "ssh://testing" pull
    - docker-compose -H "ssh://testing" down
    - docker-compose -H "ssh://testing" up -d
    - sleep 5
    - docker-compose -H "ssh://testing" top
  only:
    - main
  tags:
    - websocket
  stage: deploy-testing
