{
 "title": "Websocket Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory System",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Go Routines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rooms Realtime Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "clients_in_room", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Realtime Clients by Channel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clients_in_room", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clients Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clients_in_room", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Room Stack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "clients_in_room", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed Authentications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "failed_authentication_total", "legendFormat": "__auto" }
   ]
  }
 ]
}