Server:
  Host: websocket_app_1
  Port: 8080
  Environment: local # production, local

Redis:
  Host: redis-server
  Port: 6379
  User:
  Pass:
  ServicesRedisKey: Services

Kafka:
  Host: kafka # 192.168.130.4
  Port: 9092 #29092
  Group: ws-group
  AuthsGroup: auths-consumer-group
  ResponseTopic: websocket_response_topic
  ResponsePartitionsCount: 1
  ResponseReplicationFactor: 1
  CorrelationIdKey: correlation_id

AuthServer:
  WebsocketAuthenticationTopic: gateway_authentication_topic
  AuthenticationKey: get_device_id_by_headers
  AuthenticationTopic: auths_public
  AuthenticationPrivateTopic: auths_private
  LoginKey: access_token_generated
  LogoutKey: user_logged_out
  TTL: 3 # in minutes
  TIMEOUT: 20 # in seconds

Sentry:
  DSN: "https://5f3be1a360174839ae243a1f1344866d@o4503970402992128.ingest.sentry.io/4503970404302848"
  Environment: local
  Debug: true

Topics:
  Health: health-topic
  PublicTopic: websocket_public_topic

Security:
  ValidOrigins:
  # - "localhost"
  # - "127.0.0.1"

RateLimiter:
  Active: false
  Rate: 10 # per period
  Period: 1 # in minutes

Debug:
  Active: false
  GC: true
  Allocation: true